### PR TITLE
Remove unused or redundant dependencies

### PR DESCRIPTION
**Pull request by J0WI**
`curl` and `openssl` are already included in the base image.
`patch` was already in the template, but has not yet been applied to the Dockerfiles.

### CODE REVIEW

**Comment by alcohol** [comment]
Modifying the old `Dockerfile`s is essentially pointless since the hub images are built based on a `Dockerfile` and their relevant commit-ref which can be found here: https://github.com/docker-library/official-images/blob/master/library/composer

Of course, we can modify those commit-refs; but I am not sure if we want to overwrite existing Docker hub tags (though I am not exactly opposed to the idea either).

**Comment by alcohol** [comment]
Also, while I understand that `openssl` and `curl` may be a part of the base image, does it hurt to explicitly declare them since we do **need** them? In other words, can you guarantee me that those will always be available if we do not explicitly declare them in our own `Dockerfile`?

Be aware, that if you give me this guarantee, I will immortalize your answer in a commit message :P

**Comment by alcohol** [comment]
I like the `scanelf` addition though to determine run deps.

**Comment by J0WI** [comment]
As long as PHP-cURL is built with the base image, cURL is included [[1]](https://github.com/docker-library/php/blob/master/7.2/alpine3.7/cli/Dockerfile#L134)[[2]](https://github.com/docker-library/php/blob/master/7.2/alpine3.7/cli/Dockerfile#L22-L29). In this case it's a bit unfavorable that `openssl` is installed and the upstream images uses `libressl`. It's easier to just relay on the base image, whatever ssl library they are using.
If something would change in the upstream image, Travis will make some noise here before everything is broken. The same would happen if there were any breaking changes in `docker-php-ext-install` etc.

> Of course, we can modify those commit-refs; but I am not sure if we want to overwrite existing Docker hub tags (though I am not exactly opposed to the idea either).

Of course you should for supported versions. Otherwise none of the (security) patches in the base images get applied to the containers. This can be harmful!

**Comment by alcohol** [comment]
Alright, fair enough.

**Pull request merged**
