### PR TITLE
Keep verification keys inside the container

### PR DESCRIPTION
**Pull request by 1ed**
This way the downloaded verification keys will be available inside
the container and can be used at runtime eg. in entrypoint
scripts.

... like this:
```bash
if [ ! -f "$COMPOSER_HOME/.docker-setup" ]; then
    cp --recursive /composer/* "$COMPOSER_HOME"
    composer config -g github-oauth.github.com $GUTHUB_OAUTH_TOKEN
    composer global require "hirak/prestissimo"
    composer diagnose
    echo $(date) > "$COMPOSER_HOME/.docker-setup"
fi
```

### CODE REVIEW

**Comment by alcohol** [comment]
Please do not change the default home directory of `/tmp`.

**Comment by alcohol** [comment]
Also, using `diagnose` in the build stage is maybe not the best idea since it will generally create an error or warning, and thus fails the build (unless you resolve all of those).

**Comment by 1ed** [comment]
Done

**Comment by 1ed** [comment]
Thanks! When will it be available in the official builds?

**Comment by alcohol** [comment]
As soon as a new tag is made/pushed.

**Pull request merged**
