### PR TITLE
fix(global) adding gosu and temporary user

### PR DESCRIPTION
**Pull request by mario21ic**
The new way to use is:
docker run --rm --interactive --tty \
-e DEV_UID=$(id -u) -e DEV_GID=$(id -g) \
--volume $PWD:/app \
--volume $SSH_AUTH_SOCK:/ssh-auth.sock \
--env SSH_AUTH_SOCK=/ssh-auth.sock \
composer:1.3 install --help

### CODE REVIEW

**Comment by alcohol** [comment]
Sorry, but I am not sure this functionality belongs in the base image. Also, if you need this functionality, I highly recommend you look at [`su-exec`](https://github.com/ncopa/su-exec) instead, which is a base package you can install using `apk`, offers the same functionality and is a bit smaller.

**Comment by mario21ic** [comment]
Ok, done :)

**Comment by alcohol** [comment]
Can you present a reasonable use-case? One that justifies this change belonging in the base image, and not in a custom Dockerfile that extends the base image? Any motivation at all? Because currently I see very little reason to actually add this to the base image.

**Comment by mario21ic** [comment]
Well, the main reason is to fix a bug, when I combine "user" with "private repository":
docker run --rm --interactive --tty \
--user $(id -u):$(id -g) \
--volume $PWD:/app \
--volume $SSH_AUTH_SOCK:/ssh-auth.sock \
--env SSH_AUTH_SOCK=/ssh-auth.sock \
composer install

I got error, this is because git not found the User with UID in /etc/passwd

**Comment by alcohol** [comment]
Use `--volume /etc/passwd:/etc/passwd:ro --volume /etc/group:/etc/group:ro`.

**Comment by mario21ic** [comment]
Good point, but that is not insecure?

**Comment by alcohol** [comment]
Why would it be insecure? You are running this container for a single command.

**Comment by mario21ic** [comment]
Well, I understand :+1:

**Pull request closed without merging**
