### PR TITLE
Enhancement: Prepare release for `2.7.1`

### LINKED ISSUE #319: New Composer tag: 2.7.0
https://github.com/composer/composer/releases/tag/2.7.0

### LINKED ISSUE #325: New Composer tag: 2.7.1
https://github.com/composer/composer/releases/tag/2.7.1

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] prepares the release for `2.7.1`

Fixes #325.

### CODE REVIEW

**Comment by alcohol** [comment]
Hmm, something changed in 2.7.0 that the build does not like..

**Comment by alcohol** [comment]
Checked with @Seldaek , it seems `diagnose` in phar builds is broken in `2.7.0`.

We could skip the diagnose step in the build process, or wait for `2.7.1`.

**Comment by Seldaek** [comment]
Fixed in https://github.com/composer/composer/commit/6335551cc28026d1974740b03c4046ab6c0d3a90 fwiw

**Comment by alcohol** [comment]
@Seldaek Thanks! We will wait for `2.7.1`, development / unversioned commit releases are not really suitable for docker.

@localheinz I will try to merge this asap if you can update it when `2.7.1` is released.

**Comment by Seldaek** [comment]
I'll tag 2.7.1 tomorrow for sure

**Comment by Seldaek** [comment]
2.7.1 is now out with the fix

**Comment by localheinz** [comment]
Thank you, @Seldaek!

**Comment by alcohol** [comment]
I will update the relevant files / code for the official image tomorrow when I get home.

**Comment by localheinz** [comment]
Thank you, @alcohol and @Seldaek!

**Comment by louismariegaborit** [comment]
Thanks ! :)

A tag is scheduling today ?

**Comment by alcohol** [comment]
`2.7.1` was merged and released yesterday on the community releases channel. I prepared the official release today; see https://github.com/docker-library/official-images/pull/16227

**Pull request merged**
