### PR TITLE
Create empty world-writable cache folder

### PR DESCRIPTION
**Pull request by t3easy**
Resolves: #55

### CODE REVIEW

**Comment by alcohol** [comment]
I am confused. Why do you need this? The default `COMPOSER_HOME` directory is `/tmp` in our container. So if you just mount your host `COMPOSER_HOME` directory onto `/tmp`, you will have cache and everything else as well.

**Comment by t3easy** [comment]
Because I don't need anything else but the cache. If I mount the hole `COMPOSER_HOME` I also get the global packages.

**Comment by alcohol** [comment]
OK. But I would like to point out that this container is not built for you; it is a generic solution that serves the masses. If you want something that tailors specifically to your needs, I suggest you built your own container :-)

**Comment by alcohol** [comment]
And I do not understand how it hurts to just mount your `COMPOSER_HOME`.

**Comment by t3easy** [comment]
Because of `/tmp/composer.json`, `/tmp/composer.lock`, `/tmp/vendor` that can exist in build container if global packages are installed. They should not be shared between containers.

**Comment by alcohol** [comment]
So then what is wrong with `--volume cache:/tmp` ?

**Comment by t3easy** [comment]
Think of one `composer` container w/o packages starts and creates the `cache` volume, the next container with tool x starts with the same volume to share cache. Then the tool is missing because the volume is already filled with data of container one.
Or you have to use multiple tools in different containers because of dependencies, they will affect each other. The only neutral thing, that doesn't have side effects is the cache folder.

**Comment by alcohol** [comment]
I am sorry, but this specific use-case simply is not something we aim to support. Fortunately it is very easy to extend an existing container and implement your specific needs. :-)

**Comment by t3easy** [comment]
I've already images that solves my specific needs but thought it's helpful for others running into similar problems to fix that upstream by simple create an empty folder.

**Pull request closed without merging**
