### PR TITLE
Multi arch matrix pipeline

### PR DESCRIPTION
**Pull request by alcohol**
- [x] setup multi arch pipeline for
  - [x] current
  - [x] lts
  - [x] ~previous versions~ (or just remove these?)
  - [x] v1 (~or just remove?~)

### CODE REVIEW

**Comment by alcohol** [comment]
@crazy-max I hope I am not imposing here; I am trying to wrap my head around setting up multi-arch builds for our non-official images. I have looked at various documentation sources and your repository which was also referenced somewhere as an example. But I am not sure I am getting it.. any pointers on where I might be overlooking something would be greatly appreciated. Right now I managed to get the digests pushed, and the manifest merged, but labels (or annotations for multi-arch ?) seem to be missing still. I am also seeing an `unknown/unknown` arch when I look at the tagged versions over at https://github.com/composer/docker/pkgs/container/docker/ which I cannot figure out where it is coming from.

There is also the minor added complexity of having to have builds based on tags/source from another repository ([composer/composer](https://github.com/composer/composer)) using:
- multiple directories / workflows;
- multiple container repositories to push to; 
- two different build outputs (based on target).

Sources I have referenced:

- https://docs.docker.com/build/building/multi-platform/
- https://docs.docker.com/build/ci/github-actions/multi-platform/
- https://docs.docker.com/build/ci/github-actions/push-multi-registries/
- https://github.com/crazy-max/docker-linguist/blob/master/.github/workflows/build.yml

**Comment by tianon** [comment]
Perhaps https://github.com/moby/buildkit/blob/ff1674a396491e55667a2a840352932993a0043a/docs/attestations/attestation-storage.md is a helpful link for you 👀

**Comment by alcohol** [comment]
Honestly? Not really..

I do not really have enough spare time to dive very deep into this subject matter. I find it rather complex and not easy to comprehend. Things seems to work in the current shape of this PR though according to an end user who requested this feature, so I guess sufficient copy&paste and trial&error will make do for now :sweat_smile:

**Comment by tianon** [comment]
Hah, fair! 💕

**Pull request merged**
