### PR TITLE
Remove bash, coreutils and patch and relay on BusyBox instead

### PR DESCRIPTION
**Pull request by J0WI**
Note: all scripts need to be POSIX compatible (avoid bashisms or GNU extensions).

### CODE REVIEW

**Comment by alcohol** [comment]
No thanks.

**Comment by J0WI** [comment]
> No thanks.

@alcohol any particular reason?

I think the [change in the entrypoint script](https://github.com/composer/docker/pull/111/files#diff-dc436b1f8b06ed8110935deb04e022da) fixes a bug since you call the entrypoint explicitly with `/bin/sh`:
https://github.com/composer/docker/blob/719eb94597f3608c4933fd781d2a8448f840d277/Dockerfile.template#L62

**Comment by alcohol** [comment]
The entrypoint could be improved yes. But we definitely do not want to limit the base image to busybox tooling. Patch provided by busybox for example is not compatible with what Composer needs.

**Comment by J0WI** [comment]
Should I open a new PR for the entrypoint?

**Comment by alcohol** [comment]
Yes please :-)

**Comment by J0WI** [comment]
Fixed in #112

**Pull request closed without merging**
